$(document).ready(function(){
	$('.tick').on('change',function(){
		if($(this).is(':checked')){
			$('.customText').fadeIn(500);
		}
		else{
			$('.customText').fadeOut(500);
		}
	});
	$('.customText').trigger('change');
});
